/*
 * Google Apps Script — login endpoint for the static GitHub Pages frontend.
 *
 * IMPORTANT:
 * - Set SPREADSHEET_ID in Script Properties (Project Settings).
 * - Create a sheet named Users with columns:
 *   Username | Salt | PasswordHash | Active
 * - Store a PBKDF2-derived password hash generated by a trusted setup process.
 * - Deploy as a Web app, execute as you, and configure access deliberately.
 *
 * Apps Script's built-in Utilities has SHA-256 but not a native PBKDF2 helper.
 * This starter therefore expects the stored hash to be SHA-256(salt + ":" + password).
 * This is a basic personal-use example, NOT a robust password-storage scheme.
 * Use a long, unique password and do not reuse it elsewhere. For stronger password
 * storage, replace verifyPassword_ with a vetted PBKDF2 implementation.
 */

const TOKEN_TTL_SECONDS = 60 * 60;
const USERS_SHEET_NAME = "Users";
const TOKEN_PREFIX = "bill_session_";

function doGet() {
  return json_({
    success: true,
    service: "Personal Bill Creator API",
    message: "API is running. Use POST for login."
  });
}

function doPost(e) {
  try {
    const bodyText = e && e.postData && e.postData.contents;
    if (!bodyText) return json_({ success: false, message: "Missing request body." });

    const request = JSON.parse(bodyText);
    if (request.action === "login") return login_(request);

    return json_({ success: false, message: "Unsupported action." });
  } catch (err) {
    console.error(err);
    return json_({ success: false, message: "Request could not be processed." });
  }
}

function login_(request) {
  const username = String(request.username || "").trim();
  const password = String(request.password || "");

  if (!username || !password || username.length > 80 || password.length > 200) {
    return json_({ success: false, message: "Invalid username or password." });
  }

  const sheet = getUsersSheet_();
  const rows = sheet.getDataRange().getValues();
  if (rows.length < 2) {
    return json_({ success: false, message: "Invalid username or password." });
  }

  const headers = rows[0].map(v => String(v).trim());
  const usernameCol = headers.indexOf("Username");
  const saltCol = headers.indexOf("Salt");
  const hashCol = headers.indexOf("PasswordHash");
  const activeCol = headers.indexOf("Active");

  if ([usernameCol, saltCol, hashCol, activeCol].some(i => i < 0)) {
    throw new Error("Users sheet is missing required headers.");
  }

  const normalized = username.toLowerCase();
  let matched = null;
  for (let i = 1; i < rows.length; i++) {
    if (String(rows[i][usernameCol]).trim().toLowerCase() === normalized) {
      matched = rows[i];
      break;
    }
  }

  // Use the same outward error for unknown users and wrong passwords.
  if (!matched || !isActive_(matched[activeCol])) {
    Utilities.sleep(250);
    return json_({ success: false, message: "Invalid username or password." });
  }

  const salt = String(matched[saltCol]);
  const storedHash = String(matched[hashCol]);
  const suppliedHash = hashPassword_(salt, password);

  if (!constantTimeEqual_(storedHash, suppliedHash)) {
    Utilities.sleep(250);
    return json_({ success: false, message: "Invalid username or password." });
  }

  const token = Utilities.getUuid().replace(/-/g, "") +
                Utilities.getUuid().replace(/-/g, "");
  const expiresAt = Date.now() + TOKEN_TTL_SECONDS * 1000;

  // Store only a hash of the bearer token, not the token itself.
  const tokenHash = sha256Hex_(token);
  const cache = CacheService.getScriptCache();
  cache.put(TOKEN_PREFIX + tokenHash, JSON.stringify({
    username: normalized,
    expiresAt: expiresAt
  }), TOKEN_TTL_SECONDS);

  return json_({
    success: true,
    token: token,
    expiresAt: expiresAt,
    expiresIn: TOKEN_TTL_SECONDS
  });
}

function getUsersSheet_() {
  const spreadsheetId = PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID");
  if (!spreadsheetId) throw new Error("Set SPREADSHEET_ID in Script Properties.");
  const spreadsheet = SpreadsheetApp.openById(spreadsheetId);
  const sheet = spreadsheet.getSheetByName(USERS_SHEET_NAME);
  if (!sheet) throw new Error("Users sheet was not found.");
  return sheet;
}

function hashPassword_(salt, password) {
  return sha256Hex_(salt + ":" + password);
}

function sha256Hex_(value) {
  const bytes = Utilities.computeDigest(
    Utilities.DigestAlgorithm.SHA_256,
    value,
    Utilities.Charset.UTF_8
  );
  return bytes.map(b => (b < 0 ? b + 256 : b).toString(16).padStart(2, "0")).join("");
}

function constantTimeEqual_(a, b) {
  a = String(a);
  b = String(b);
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return result === 0;
}

function isActive_(value) {
  return value === true || String(value).trim().toLowerCase() === "true" ||
         String(value).trim() === "1";
}

function json_(object) {
  return ContentService
    .createTextOutput(JSON.stringify(object))
    .setMimeType(ContentService.MimeType.JSON);
}

/*
 * Run this manually once from the Apps Script editor to create a salted
 * SHA-256 record for the initial user. Replace the sample values first.
 *
 * This is only for bootstrapping. Do not publish real credentials or commit
 * them to a public repository. Run it, then remove the real password from code.
 */
function setupInitialUserExample_() {
  const username = "REPLACE_WITH_YOUR_USERNAME";
  const password = "REPLACE_WITH_A_LONG_UNIQUE_PASSWORD";
  const salt = Utilities.getUuid() + Utilities.getUuid();
  const passwordHash = hashPassword_(salt, password);

  const sheet = getUsersSheet_();
  if (sheet.getLastRow() === 0) {
    sheet.appendRow(["Username", "Salt", "PasswordHash", "Active"]);
  }
  sheet.appendRow([username, salt, passwordHash, true]);
}
